### ISSUE TITLE
Subtitles overlapping title

### ISSUE THREAD

**Issue by azizLIGHT** [t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame#2] opened 2023-06-26 18:35 UTC
The subtitles are not in their own blank space but are instead overlapping the video title. When I toggle the subtitles, I can see the blank area being created for the subtitles to exist in, but it is misaligned and near the comments area instead. The video can explain better:
[Kooha-2023-06-26-14-31-20.webm](https://github.com/t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame/assets/8013867/c288e85b-6955-41cd-9590-37fc145bc559)

**Comment by T1mL3arn** [comment] 2023-06-27 02:31
For me it works the same way as intended. I need more info:

- Do you have any other userscripts/userstyles/extensions that might affect youtube styling? 
- Maybe some youtube settings that enables new appearance?
- From what country are you visiting youtube ? I assume there might be different styles for different locations

**Comment by azizLIGHT** [comment] 2023-06-27 04:51
- I'm using Firefox 114.0 on a new profile with Tampermonkey 4.18.1 with default settings and no other addons or extensions or adblockers. It's basically as untouched as can be. However my other firefox profile with many addons and scripts and extensions also behaves the same way. Worth mentioning that I am not on Windows (using Linux)
- I am not signed into youtube and have not set any settings there. When signed in (with whatever settings there may be), I also saw the same behavior
- Visiting youtube from USA. I don't have a way to test this right now

Hope that helps!

**Comment by azizLIGHT** [comment] 2023-06-27 05:43
I also tried it in a barebones chromium browser and see the same issue. Here are those screenshots:

- Here the subtitles appear over a current event's "Context" section, as well as above the title and description, but still creates the gap between the description and next recommended video. The gap is where the mouse cursor is. In this situation its easier to read the subtitles but this is not always the case
![image](https://github.com/t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame/assets/8013867/a14d87ef-ad02-42e6-8a37-ab0a60ea38f4)


- Here there is no such context section. This is before
![image](https://github.com/t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame/assets/8013867/727aa4a5-4dd5-48cc-9188-150980f870cf)


- This is after. Subtitles cover  video title and other buttons. Gap is created before the recommended videos. 
![image](https://github.com/t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame/assets/8013867/8fb5bd90-967a-4c95-b8a2-3b8ae015cbb3)


- On a wider screen, the gap is above the comments
![image](https://github.com/t1ml3arn-userscript-js/Youtube-subtitles-under-video-frame/assets/8013867/8e26dc4c-7f34-4f19-be96-1aa156aeb6a2)

**Comment by T1mL3arn** [comment] 2023-06-27 08:26
I was able to reproduce the issue without VPN. Though I don't see "context" box for titanic video.

**Comment by T1mL3arn** [comment] 2023-06-27 12:13
Fixed with v1.3.0.

**Closed as completed by T1mL3arn** 2023-06-27 12:13 UTC

**Comment by azizLIGHT** [comment] 2023-06-28 04:34
Thank you it's perfect. Appreciate the fast fix and of course for making this script in the first place
